import { FACE_TURNS, type CubieCube } from '@cube/core';
import {
  createSearcher,
  FOUND,
  MAX_DEPTH,
  STOPPED,
  type DepthStats,
  type OptimalOptions,
  type OptimalResult,
  type OptimalSolve,
  type SearchTables,
  type Searcher,
} from './optimal.ts';
import { N_MOVES } from './tables.ts';

// Parallel IDA*: every search depth is split into tasks, the moves of the first PREFIX levels,
// which the coordinator lists and all participants (coordinator and helpers) take one by one from
// a shared counter. Tables live in SharedArrayBuffers, so each worker adds only its search stack.
// Participants meet after every depth, which keeps the result optimal: no worker starts depth d + 1
// while another could still find a solution of length d.
//
// A helper takes part in a depth only if it was ready when the depth started. Browsers may not
// start a worker while its parent is blocked in Atomics.wait, so the coordinator never waits for
// a helper that has not announced itself; latecomers join at the next depth.

const PREFIX = 3;
/** Below this bound a depth takes milliseconds; splitting it would cost more than it saves. */
const PARALLEL_FROM = 13;
const MAX_TASKS = 18 * 15 * 15;
const WAIT_SLICE_MS = 100;

// Slots of the control array.
const EPOCH = 0;
const COMMAND = 1;
const BOUND = 2;
const TASK_COUNT = 3;
const NEXT_TASK = 4;
const ACTIVE = 5;
const FOUND_FLAG = 6;
const STOP_FLAG = 7;
/** Bit i set: helper i is running and waiting for depths. */
const READY_MASK = 8;
/** The helpers taking part in the current depth. */
const ROUND_MASK = 9;
const CONTROL_SLOTS = 10;
/** Helper indices are bits of an Int32 mask, after bit 0 for the coordinator. */
export const MAX_HELPERS = 30;

const SEARCH = 1;
const QUIT = 2;

/** What a helper needs, all of it structured-cloneable; the large tables are shared, not copied. */
export interface HelperInit {
  readonly index: number;
  readonly tables: SearchTables;
  readonly control: Int32Array<SharedArrayBuffer>;
  /** The root state frame of the current solve. */
  readonly root: Int32Array<SharedArrayBuffer>;
  readonly tasks: Uint8Array<SharedArrayBuffer>;
  readonly solution: Uint8Array<SharedArrayBuffer>;
  /** Nodes generated by each participant, written by its owner. */
  readonly nodes: Float64Array<SharedArrayBuffer>;
}

/**
 * Long-lived helper threads. `start` hands a helper an init to run {@link runHelper} with; a
 * helper returns from it when its solver is disposed and can then take the next init.
 */
export interface HelperPool {
  readonly size: number;
  start(init: HelperInit): void;
  terminate(): void;
}

interface Shared {
  readonly control: Int32Array<SharedArrayBuffer>;
  readonly root: Int32Array<SharedArrayBuffer>;
  readonly tasks: Uint8Array<SharedArrayBuffer>;
  readonly solution: Uint8Array<SharedArrayBuffer>;
  readonly nodes: Float64Array<SharedArrayBuffer>;
}

/** Takes tasks until none are left, a solution is found or the search is stopped. */
function work(searcher: Searcher, shared: Shared, report: () => void): void {
  const { control, tasks, solution } = shared;
  const bound = control[BOUND];
  const count = control[TASK_COUNT];
  for (;;) {
    const task = Atomics.add(control, NEXT_TASK, 1);
    if (task >= count) break;
    if (Atomics.load(control, FOUND_FLAG) !== 0 || Atomics.load(control, STOP_FLAG) !== 0) break;
    // Listed prefixes passed every bound when they were listed, so they replay without pruning.
    let lastFace = -1;
    for (let depth = 0; depth < PREFIX; depth++) {
      const m = tasks[task * PREFIX + depth];
      searcher.descend(depth, bound - depth, m);
      searcher.path[depth] = m;
      lastFace = (m / 3) | 0;
    }
    const outcome = searcher.search(PREFIX, bound - PREFIX, lastFace);
    report();
    if (outcome === FOUND) {
      if (Atomics.compareExchange(control, FOUND_FLAG, 0, 1) === 0) {
        solution.set(searcher.path.subarray(0, bound));
      }
      break;
    }
    if (outcome === STOPPED) break;
  }
  report();
}

/** The body of a helper thread: waits for each depth, works on it, reports, until told to quit. */
export function runHelper(init: HelperInit): void {
  const shared: Shared = init;
  const { control, root } = shared;
  const stopped = () =>
    Atomics.load(control, FOUND_FLAG) !== 0 || Atomics.load(control, STOP_FLAG) !== 0;
  // The searcher counts across solves; the shared slot holds this solve's count, which the
  // coordinator zeroes before a solve's first depth.
  let base = 0;
  let reported = 0;
  const report = () => {
    shared.nodes[init.index] = reported + searcher.nodes - base;
  };
  const searcher = createSearcher(init.tables, () => {
    report();
    return stopped();
  });
  const bit = 1 << init.index;
  Atomics.or(control, READY_MASK, bit);
  let epoch = 0;
  for (;;) {
    Atomics.wait(control, EPOCH, epoch);
    epoch = Atomics.load(control, EPOCH);
    if (Atomics.load(control, COMMAND) === QUIT) return;
    if ((Atomics.load(control, ROUND_MASK) & bit) === 0) continue;
    base = searcher.nodes;
    reported = shared.nodes[init.index];
    searcher.copyRoot(root);
    work(searcher, shared, report);
    if (Atomics.sub(control, ACTIVE, 1) === 1) Atomics.notify(control, ACTIVE);
  }
}

function bitCount(mask: number): number {
  let count = 0;
  for (let m = mask; m !== 0; m &= m - 1) count++;
  return count;
}

function sharedArray<T>(make: (buffer: SharedArrayBuffer) => T, bytes: number): T {
  return make(new SharedArrayBuffer(bytes));
}

/**
 * The optimal solver spread over the coordinator's thread and the pool's helpers. Node counts of
 * completed depths equal the sequential solver's; at the last depth they depend on timing, and so
 * may the solution, which is optimal either way.
 */
export function createParallelOptimalSolver(
  tables: SearchTables,
  pool: HelperPool,
): OptimalSolve & { readonly dispose: () => void } {
  if (pool.size > MAX_HELPERS) throw new RangeError(`At most ${String(MAX_HELPERS)} helpers`);
  const participants = pool.size + 1;
  const shared: Shared = {
    control: sharedArray((b) => new Int32Array(b), CONTROL_SLOTS * 4),
    root: sharedArray((b) => new Int32Array(b), 64 * 4),
    tasks: sharedArray((b) => new Uint8Array(b), MAX_TASKS * PREFIX),
    solution: sharedArray((b) => new Uint8Array(b), MAX_DEPTH),
    nodes: sharedArray((b) => new Float64Array(b), participants * 8),
  };
  for (let i = 1; i < participants; i++) pool.start({ index: i, tables, ...shared });
  const { control } = shared;

  const solve = (cube: CubieCube, options: OptimalOptions = {}): OptimalResult => {
    const { shouldStop, onProgress, upperBound } = options;
    const begin = performance.now();
    const depths: DepthStats[] = [];
    let bound = 0;
    // An object, not a local: the flag is set inside callbacks the type checker cannot follow.
    const stop = { cancelled: false };
    let listNodes = 0;

    const helperNodes = () => {
      let sum = 0;
      for (let i = 1; i < participants; i++) sum += shared.nodes[i];
      return sum;
    };
    const totalNodes = () => listNodes + searcher.nodes + helperNodes();
    const poll = (): boolean => {
      onProgress?.({ depth: bound, nodes: totalNodes(), elapsedMs: performance.now() - begin });
      if (shouldStop?.() === true) {
        stop.cancelled = true;
        Atomics.store(control, STOP_FLAG, 1);
      }
      return stop.cancelled || Atomics.load(control, FOUND_FLAG) !== 0;
    };
    const searcher = createSearcher(tables, poll);
    bound = searcher.setRoot(cube);
    shared.root.set(searcher.state.subarray(0, shared.root.length));
    shared.nodes.fill(0);
    control[STOP_FLAG] = 0;

    const result = (moves: OptimalResult['moves'], provedBound = false): OptimalResult => ({
      moves,
      cancelled: stop.cancelled,
      provedBound,
      nodes: totalNodes(),
      elapsedMs: performance.now() - begin,
      depths,
    });

    /** Lists the prefixes that pass every bound, generating their nodes as the search would. */
    function listTasks(depth: number, togo: number, lastFace: number, count: number): number {
      if (depth === PREFIX) {
        shared.tasks.set(searcher.path.subarray(0, PREFIX), count * PREFIX);
        return count + 1;
      }
      for (let m = 0; m < N_MOVES; m++) {
        const face = (m / 3) | 0;
        const diff = lastFace - face;
        if (diff === 0 || diff === 3) continue;
        listNodes++;
        if (!searcher.descend(depth, togo, m)) continue;
        searcher.path[depth] = m;
        count = listTasks(depth + 1, togo - 1, face, count);
      }
      return count;
    }

    for (; bound <= MAX_DEPTH; bound++) {
      if (upperBound !== undefined && bound >= upperBound.length) return result(upperBound, true);
      if (poll()) return result(undefined);
      const depthStart = performance.now();
      const nodesBefore = totalNodes();
      let found: boolean;
      if (bound < PARALLEL_FROM) {
        const outcome = searcher.search(0, bound, -1);
        if (outcome === STOPPED) return result(undefined);
        found = outcome === FOUND;
        if (found) shared.solution.set(searcher.path.subarray(0, bound));
      } else {
        const count = listTasks(0, bound, -1, 0);
        control[BOUND] = bound;
        control[TASK_COUNT] = count;
        control[NEXT_TASK] = 0;
        control[FOUND_FLAG] = 0;
        control[COMMAND] = SEARCH;
        const ready = Atomics.load(control, READY_MASK);
        control[ROUND_MASK] = ready;
        Atomics.store(control, ACTIVE, 1 + bitCount(ready));
        Atomics.add(control, EPOCH, 1);
        Atomics.notify(control, EPOCH);
        work(searcher, shared, () => undefined);
        Atomics.sub(control, ACTIVE, 1);
        // Wait for the helpers, still reporting progress and passing on cancellation.
        for (;;) {
          const active = Atomics.load(control, ACTIVE);
          if (active === 0) break;
          Atomics.wait(control, ACTIVE, active, WAIT_SLICE_MS);
          poll();
        }
        if (stop.cancelled) return result(undefined);
        found = Atomics.load(control, FOUND_FLAG) !== 0;
      }
      depths.push({
        depth: bound,
        nodes: totalNodes() - nodesBefore,
        ms: performance.now() - depthStart,
      });
      if (found) {
        return result(Array.from(shared.solution.subarray(0, bound), (m) => FACE_TURNS[m]));
      }
    }
    throw new Error(`No solution within ${String(MAX_DEPTH)} moves`);
  };

  // The pool outlives the solver: helpers return to their message loop for the next init.
  return Object.assign(solve, {
    dispose: () => {
      control[COMMAND] = QUIT;
      Atomics.add(control, EPOCH, 1);
      Atomics.notify(control, EPOCH);
    },
  });
}
