import {
  CORNER_FACELETS,
  CORNER_FACES,
  EDGE_FACELETS,
  EDGE_FACES,
  faceletAt,
  FACES,
  faceNormal,
  faceWithNormal,
  stickerAt,
  type Vec3,
} from '@cube/core';
import { getTwist, N_TWIST, setTwist } from './coordinates.ts';

/** A 3×3 orthogonal integer matrix, row by row. */
type Matrix = readonly number[];

const IDENTITY: Matrix = [1, 0, 0, 0, 1, 0, 0, 0, 1];

// D4h, the 16 symmetries of the cube that keep the U/D axis (Kociemba,
// https://kociemba.org/math/symmetric.htm), generated by a quarter turn about it like U, a half
// turn about the F/B axis, and the mirror image that swaps R and L. x points to R, y to U, z to F.
const GENERATORS: readonly Matrix[] = [
  [0, 0, -1, 0, 1, 0, 1, 0, 0], // (x, y, z) → (−z, y, x): front goes left, as with U
  [-1, 0, 0, 0, -1, 0, 0, 0, 1], // (x, y, z) → (−x, −y, z)
  [-1, 0, 0, 0, 1, 0, 0, 0, 1], // (x, y, z) → (−x, y, z)
];

const apply = (m: Matrix, [x, y, z]: Vec3): Vec3 => [
  m[0] * x + m[1] * y + m[2] * z,
  m[3] * x + m[4] * y + m[5] * z,
  m[6] * x + m[7] * y + m[8] * z,
];

/** a · b: first b, then a. */
function compose(a: Matrix, b: Matrix): Matrix {
  const out: number[] = [];
  for (let r = 0; r < 3; r++) {
    for (let c = 0; c < 3; c++) {
      out.push(a[r * 3] * b[c] + a[r * 3 + 1] * b[3 + c] + a[r * 3 + 2] * b[6 + c]);
    }
  }
  return out;
}

const sameMatrix = (a: Matrix, b: Matrix) => a.every((v, i) => v === b[i]);

function closure(generators: readonly Matrix[]): Matrix[] {
  const group: Matrix[] = [IDENTITY];
  // The array iterator also visits elements pushed while iterating.
  for (const element of group) {
    for (const g of generators) {
      const product = compose(g, element);
      if (!group.some((m) => sameMatrix(m, product))) group.push(product);
    }
  }
  return group;
}

const MATRICES = closure(GENERATORS);

export const N_SYM = 16;
if (MATRICES.length !== N_SYM) throw new Error(`D4h has ${String(MATRICES.length)} elements`);

const STICKERS = 54;
const UNKNOWN_EDGE = 255;

/**
 * One symmetry of the cube. Conjugating a state X by it moves every sticker to its image under
 * the symmetry and recolours it with the image of its colour, which gives X as seen through a
 * rotated or mirrored cube: the same state for every purpose of a search.
 */
export interface Symmetry {
  readonly mirror: boolean;
  /** Facelet each sticker moves to. */
  readonly stickerTo: Uint8Array;
  /** Face index each face (and colour) moves to. */
  readonly faceTo: Uint8Array;
  /**
   * The solved cube's edges moved by the symmetry without recolouring, as an edge permutation R
   * (position i holds edge ep[i] with flip eo[i]), and its inverse. Edges have no handedness, so
   * this holds for mirror images too, and conjugation is R⁻¹ · X · R.
   */
  readonly ep: Uint8Array;
  readonly eo: Uint8Array;
  readonly inverseEp: Uint8Array;
  readonly inverseEo: Uint8Array;
}

function determinant(m: Matrix): number {
  return (
    m[0] * (m[4] * m[8] - m[5] * m[7]) -
    m[1] * (m[3] * m[8] - m[5] * m[6]) +
    m[2] * (m[3] * m[7] - m[4] * m[6])
  );
}

function symmetry(matrix: Matrix): Symmetry {
  const stickerTo = new Uint8Array(STICKERS);
  for (let p = 0; p < STICKERS; p++) {
    const { position, normal } = stickerAt(3, p);
    stickerTo[p] = faceletAt(3, {
      position: apply(matrix, position),
      normal: apply(matrix, normal),
    });
  }
  const faceTo = Uint8Array.from(FACES, (face) =>
    FACES.indexOf(faceWithNormal(apply(matrix, faceNormal(face)))),
  );

  // Where each sticker of the solved cube lands, keeping its colour.
  const moved = new Uint8Array(STICKERS);
  for (let p = 0; p < STICKERS; p++) moved[stickerTo[p]] = Math.floor(p / 9);
  const edgeFaces = EDGE_FACES.map((faces) => faces.map((f) => FACES.indexOf(f)));
  const ep = new Uint8Array(12).fill(UNKNOWN_EDGE);
  const eo = new Uint8Array(12);
  EDGE_FACELETS.forEach(([a, b], position) => {
    const shown = [moved[a], moved[b]];
    const edge = edgeFaces.findIndex(([x, y]) => shown.includes(x) && shown.includes(y));
    ep[position] = edge;
    eo[position] = shown[0] === edgeFaces[edge][0] ? 0 : 1;
  });
  if (ep.includes(UNKNOWN_EDGE)) throw new Error('A symmetry did not map edges to edges');
  const inverseEp = new Uint8Array(12);
  const inverseEo = new Uint8Array(12);
  for (let i = 0; i < 12; i++) {
    inverseEp[ep[i]] = i;
    inverseEo[ep[i]] = eo[i];
  }
  return {
    mirror: determinant(matrix) < 0,
    stickerTo,
    faceTo,
    ep,
    eo,
    inverseEp,
    inverseEo,
  };
}

export const D4H: readonly Symmetry[] = MATRICES.map(symmetry);

/** Index of each symmetry's inverse: for an orthogonal matrix, its transpose. */
export const INVERSE_SYM: Uint8Array = Uint8Array.from(MATRICES, (m) => {
  const transpose = [m[0], m[3], m[6], m[1], m[4], m[7], m[2], m[5], m[8]];
  return MATRICES.findIndex((other) => sameMatrix(other, transpose));
});

/** Conjugates a state given as 54 face indices (0..5 in U, R, F, D, L, B order). */
export function conjugateFaces(faces: ArrayLike<number>, s: number, out: Uint8Array): void {
  const { stickerTo, faceTo } = D4H[s];
  for (let p = 0; p < STICKERS; p++) out[stickerTo[p]] = faceTo[faces[p]];
}

/** Conjugates the edges of a state: R⁻¹ · X · R in the cubie multiplication of @cube/core. */
export function conjugateEdges(
  s: number,
  ep: ArrayLike<number>,
  eo: ArrayLike<number>,
  outEp: Uint8Array,
  outEo: Uint8Array,
): void {
  const sym = D4H[s];
  for (let i = 0; i < 12; i++) {
    const j = sym.ep[i];
    const edge = ep[j];
    outEp[i] = sym.inverseEp[edge];
    outEo[i] = sym.inverseEo[edge] ^ eo[j] ^ sym.eo[i];
  }
}

const cornerFaces = CORNER_FACES.map((faces) => faces.map((f) => FACES.indexOf(f)));
const U = 0;
const D = 3;

/**
 * twistConj[twist · 16 + s] is the twist of the state conjugated by s. Every symmetry in D4h keeps
 * U and D stickers on U and D, so the result does not depend on where the corners are; it is read
 * off the conjugated stickers, which handles mirror images without special cases.
 */
export function buildTwistConjugation(): Uint16Array {
  const table = new Uint16Array(N_TWIST * N_SYM);
  const co = new Uint8Array(8);
  const faces = new Uint8Array(STICKERS);
  const conjugated = new Uint8Array(STICKERS);
  const twisted = new Uint8Array(8);
  for (let twist = 0; twist < N_TWIST; twist++) {
    setTwist(twist, co);
    for (let i = 0; i < 8; i++) {
      for (let k = 0; k < 3; k++) faces[CORNER_FACELETS[i][(k + co[i]) % 3]] = cornerFaces[i][k];
    }
    for (let s = 0; s < N_SYM; s++) {
      conjugateFaces(faces, s, conjugated);
      for (let i = 0; i < 8; i++) {
        const slots = CORNER_FACELETS[i];
        let k = 0;
        while (conjugated[slots[k]] !== U && conjugated[slots[k]] !== D) k++;
        twisted[i] = k;
      }
      table[twist * N_SYM + s] = getTwist(twisted);
    }
  }
  return table;
}
